"""Executable validation runner for AGENTICAITA paper claims."""
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

from metrics import result_to_dict, run_all_validations


def serialise(value: Any) -> str:
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


def write_json(path: Path, rows: list[dict[str, Any]]) -> None:
    path.write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["claim_id", "claim", "paper_value", "computed_value", "status", "tolerance", "notes"],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow({key: serialise(row.get(key, "")) for key in writer.fieldnames})


def write_markdown(path: Path, rows: list[dict[str, Any]]) -> None:
    counts = Counter(row["status"] for row in rows)
    lines: list[str] = []
    lines.append("# AGENTICAITA claim validation report")
    lines.append("")
    lines.append("This report was generated by a Paper2Code-style validation repository. It validates only claims that are computable from the paper's reported quantities and marks raw-data-dependent claims as unsupported.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    for status in ["pass", "qualified", "fail", "unsupported"]:
        lines.append(f"- **{status}**: {counts.get(status, 0)}")
    lines.append("")
    lines.append("## Results")
    lines.append("")
    lines.append("| Claim ID | Status | Paper value | Computed value | Notes |")
    lines.append("|---|---:|---:|---:|---|")
    for row in rows:
        lines.append(
            "| {claim_id} | {status} | {paper_value} | {computed_value} | {notes} |".format(
                claim_id=row["claim_id"],
                status=row["status"],
                paper_value=serialise(row["paper_value"]).replace("|", "\\|"),
                computed_value=serialise(row["computed_value"]).replace("|", "\\|"),
                notes=serialise(row.get("notes", "")).replace("|", "\\|"),
            )
        )
    lines.append("")
    lines.append("## Main methodological caveats")
    lines.append("")
    lines.append("1. The binomial p≈0.34 claim is reproduced by a one-sided normal approximation. The exact one-sided binomial p-value is about 0.367 and the exact two-sided p-value is about 0.735.")
    lines.append("2. The 2σ false-positive rate of 4.6% is the two-sided normal tail. The trigger is written as z_t ≥ 2.0, which is one-sided and would have a normal tail of about 2.28%. The return magnitude r_t is also non-negative, so a normal-tail interpretation needs more justification.")
    lines.append("3. The transaction-cost sensitivity table is arithmetically consistent within cents-level rounding, but it is not a validation of live execution costs because the paper reports a dry-run without order placement.")
    lines.append("4. Claims about live operation, zero human intervention, raw SQLite provenance, funding correction, and per-asset CBD effects require artefacts that are not included in the paper.")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path("results"))
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    rows = [result_to_dict(result) for result in run_all_validations()]
    write_json(args.out / "validation_results.json", rows)
    write_csv(args.out / "validation_results.csv", rows)
    write_markdown(args.out / "validation_report.md", rows)

    counts = Counter(row["status"] for row in rows)
    print("Validation complete")
    for status in ["pass", "qualified", "fail", "unsupported"]:
        print(f"{status}: {counts.get(status, 0)}")
    print(f"Report: {args.out / 'validation_report.md'}")


if __name__ == "__main__":
    main()
