#!/usr/bin/env python3
"""Report issue-native metadata hygiene warnings for GitHub issues.

The checker reads issue metadata and reports missing or contradictory labels. It
is intentionally report-only: it does not mutate issues, labels, milestones,
comments, or repository files.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REQUIRED_LABEL_FAMILIES = ("area:", "priority:", "status:")
EXCLUSIVE_LABEL_FAMILIES = ("priority:", "status:")
AGENT_READY = "agent-ready"
NEEDS_HUMAN = "needs-human"
NEEDS_ACCEPTANCE_CRITERIA = "needs-acceptance-criteria"
STATUS_BLOCKED = "status:blocked"


def fetch_issues(repo: str, state: str, limit: int) -> list[dict[str, Any]]:
    """Fetch issue metadata using the GitHub CLI."""
    if shutil.which("gh") is None:
        raise RuntimeError(
            "GitHub CLI executable 'gh' was not found. Install gh and run "
            "'gh auth login' before running the issue hygiene checker."
        )

    fields = ",".join(["labels", "number", "state", "title", "url"])
    command = [
        "gh",
        "issue",
        "list",
        "--repo",
        repo,
        "--state",
        state,
        "--limit",
        str(limit),
        "--json",
        fields,
    ]
    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as exc:
        detail = f": {(exc.stderr or '').strip()}" if exc.stderr else ""
        raise RuntimeError(
            f"Unable to fetch issues for {repo}. Check 'gh auth status' and repository access{detail}"
        ) from exc

    return parse_issue_payload(result.stdout)


def load_issues(path: str) -> list[dict[str, Any]]:
    """Load issue metadata from a JSON fixture generated by gh issue list."""
    return parse_issue_payload(Path(path).read_text(encoding="utf-8"))


def parse_issue_payload(text: str) -> list[dict[str, Any]]:
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Issue metadata was not valid JSON.") from exc
    if not isinstance(payload, list):
        raise RuntimeError("Issue metadata must be a JSON list.")
    for issue in payload:
        if not isinstance(issue, dict):
            raise RuntimeError("Each issue metadata entry must be a JSON object.")
    return payload


def label_names(issue: dict[str, Any]) -> list[str]:
    labels = []
    for label in issue.get("labels") or []:
        if isinstance(label, dict) and label.get("name"):
            labels.append(str(label["name"]))
        elif isinstance(label, str):
            labels.append(label)
    return sorted(set(labels))


def labels_with_prefix(labels: list[str], prefix: str) -> list[str]:
    return sorted(label for label in labels if label.startswith(prefix))


def warnings_for(labels: list[str]) -> list[str]:
    warnings: list[str] = []
    by_family = {prefix: labels_with_prefix(labels, prefix) for prefix in REQUIRED_LABEL_FAMILIES}

    if not by_family["area:"]:
        warnings.append("missing area:*")
    if not by_family["priority:"]:
        warnings.append("missing priority:*")
    if not by_family["status:"]:
        warnings.append("missing status:*")

    for prefix in EXCLUSIVE_LABEL_FAMILIES:
        if len(by_family[prefix]) > 1:
            warnings.append(f"multiple {prefix}* labels")

    blocked_labels = labels_with_prefix(labels, "blocked:")
    if AGENT_READY in labels and STATUS_BLOCKED in by_family["status:"]:
        warnings.append("agent-ready combined with status:blocked")
    if AGENT_READY in labels and blocked_labels:
        warnings.append("agent-ready combined with blocked:*")
    if AGENT_READY in labels and NEEDS_HUMAN in labels:
        warnings.append("agent-ready combined with needs-human")
    if AGENT_READY in labels and NEEDS_ACCEPTANCE_CRITERIA in labels:
        warnings.append("agent-ready combined with needs-acceptance-criteria")

    return warnings


def issue_sort_key(issue: dict[str, Any]) -> tuple[int, int]:
    state_rank = 0 if str(issue.get("state") or "").lower() == "open" else 1
    try:
        number = int(issue.get("number"))
    except (TypeError, ValueError):
        number = 0
    return state_rank, number


def build_report(raw_issues: list[dict[str, Any]], repo: str, state: str, source: str) -> dict[str, Any]:
    issues = []
    for raw in sorted(raw_issues, key=issue_sort_key):
        labels = label_names(raw)
        issue_warnings = warnings_for(labels)
        issues.append(
            {
                "number": int(raw.get("number") or 0),
                "title": str(raw.get("title") or ""),
                "state": str(raw.get("state") or "").lower(),
                "url": str(raw.get("url") or ""),
                "labels": labels,
                "warnings": issue_warnings,
            }
        )

    issue_count = len(issues)
    warning_issues = [issue for issue in issues if issue["warnings"]]
    warning_count = sum(len(issue["warnings"]) for issue in warning_issues)
    return {
        "schema_version": "1",
        "repository": repo,
        "state_filter": state,
        "source": source,
        "summary": {
            "issues_checked": issue_count,
            "issues_with_warnings": len(warning_issues),
            "warnings": warning_count,
        },
        "issues": issues,
    }


def markdown_link(issue: dict[str, Any]) -> str:
    number = issue["number"]
    if issue["url"]:
        return f"[#{number}]({issue['url']})"
    return f"#{number}"


def render_markdown(report: dict[str, Any]) -> str:
    summary = report["summary"]
    lines = [
        "# Issue Hygiene Report",
        "",
        "This report is generated from GitHub issue metadata. It is report-only and does not mutate issues, labels, milestones, comments, or repository files.",
        "",
        "## Source",
        "",
        f"- Repository: `{report['repository']}`",
        f"- Issue state filter: `{report['state_filter']}`",
        f"- Source: `{report['source']}`",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Issues checked | {summary['issues_checked']} |",
        f"| Issues with warnings | {summary['issues_with_warnings']} |",
        f"| Warnings | {summary['warnings']} |",
        "",
        "## Warnings",
        "",
        "| Issue | Title | Warnings |",
        "| --- | --- | --- |",
    ]
    warning_rows = [issue for issue in report["issues"] if issue["warnings"]]
    if not warning_rows:
        lines.append("| - | No metadata warnings | - |")
    else:
        for issue in warning_rows:
            warnings = ", ".join(issue["warnings"])
            lines.append(f"| {markdown_link(issue)} | {issue['title']} | {warnings} |")
    lines.append("")
    return "\n".join(lines)


def write_output(path: str, text: str) -> None:
    if path == "-":
        print(text)
        return
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"Wrote issue hygiene report to {target}", file=sys.stderr)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, help="Repository in owner/name form.")
    parser.add_argument("--state", choices=["open", "closed", "all"], default="open")
    parser.add_argument("--limit", type=int, default=200, help="Maximum issues to fetch with gh.")
    parser.add_argument("--output", default="-", help="Output path or '-' for stdout.")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    parser.add_argument(
        "--input-json",
        help="Optional path to a gh issue list JSON fixture. When set, the checker does not call gh.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit with status 1 when metadata warnings are found. Default is report-only success.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.input_json:
            raw_issues = load_issues(args.input_json)
            source = f"input-json:{args.input_json}"
        else:
            raw_issues = fetch_issues(args.repo, args.state, args.limit)
            source = "gh"
        report = build_report(raw_issues, args.repo, args.state, source)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.format == "json":
        output = json.dumps(report, indent=2) + "\n"
    else:
        output = render_markdown(report)
    write_output(args.output, output)

    if args.strict and report["summary"]["warnings"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
